---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch
  labels:
    app: pytorch
spec:
  selector:
    matchLabels:
      app: pytorch
  replicas: 1
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
        - name: pytorch
          image: jdvincent/pytorch-image-classification:latest
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis_host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis_port | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: pytorch
  selector:
    app: pytorch
  type: ClusterIP
